r"""
What an author may type, as data: every filter, global, attribute and `meta.yaml` key, with an
example that is executed rather than asserted.

The vocabulary is **182 filters and 32 globals** on the Markdown environment alone, and it was
written down nowhere. The cost is measurable: 57 of those 182 names appear anywhere in `source/`
and the other 125 are unreachable in practice, because the only way to find one is to read
`core/builder/jinja.py`. `CLAUDE.md` covers the half-dozen conventions that have cost somebody a
bug; this covers the table.

**Docstrings could not be the source**, which is why this is a table of its own rather than a
scrape. They are written for whoever maintains the code -- `num`'s explains why it is idempotent,
`_unop`'s explains contamination -- and ten filter roots have none at all. What an author needs
is "what do I type and what comes out", which is a different text about the same function.

Three things read this:

- `docs/filters.md`, generated by `python -m core.builder.reference`. `--check` regenerates and
  exits nonzero on a difference, which is the shape `core/audit/macros.py` already has.
- the editor's `/api/reference`, which is what the hover in `tools/editor/static/app.js` shows.
- `core/tests/test_reference.py`, and that is the half that makes the rest trustworthy. One test
  asserts the table's names are *exactly* the registered ones in both directions, so a filter
  added without an entry fails the suite. Another **renders every example and compares it to the
  output written beside it**, so the document cannot drift into fiction -- which is the failure
  mode of every reference maintained by hand.

Two environments, and they are **disjoint**. `MarkdownJinjaRenderer` serves `.md` (and, through
`PictureJinjaRenderer`, `.svg` and `.tikz`); `StaticRenderer` serves `.jtex`. `|disp` is written
4760 times and works only in the first; `|upnth` is written 11 times and works only in the
second. Neither fact was written down, and either mistake is found by a failed build. Every entry
says which environment it belongs to, and the editor offers only the right set for the pane.

The examples share one small context, declared in `example_context` and printed once at the head
of the document, so an example can be read without hunting for what `v` is.
"""
from __future__ import annotations

import difflib
import sys
from dataclasses import dataclass
from pathlib import Path

#: Where the generated document lives. Relative to the repository root, like everything else
#: `core` opens by path.
DOCUMENT = Path('docs/filters.md')

#: The filter roots that `MarkdownJinjaRenderer.__generate_format_functions` gives a `0`-`9`
#: family to. Declared on the entry rather than listed here; this is only the suffix set.
PRECISIONS = tuple(str(digit) for digit in range(10))

MARKDOWN = 'markdown'
STATIC = 'static'
META = 'meta'

#: The kinds an entry may be. `filter` and `global` are checked against a live environment;
#: the rest cannot be, and are checked only for internal consistency.
KINDS = ('filter', 'global', 'attribute', 'operator', 'namespace',
         'meta-key', 'values-key', 'jinja-builtin')


@dataclass(frozen=True)
class Entry:
    """
    One name an author may write.

    `example` is a template fragment and `expect` is what it renders to, in the context
    `example_context` builds. They are a pair: the test renders the one and compares it with the
    other, so neither can go stale without the suite going red.

    An entry with no `example` is one whose output is not a string worth printing -- a `meta.yaml`
    key, or a maths global whose example would be `0.5` -- and those carry a `signature` and a
    `summary` only.
    """
    name: str
    kind: str
    summary: str
    env: str = MARKDOWN
    signature: str = ''
    example: str = ''
    expect: str = ''
    note: str = ''
    #: Whether `__generate_format_functions` also registered `<name>0` ... `<name>9`.
    precisions: bool = False
    #: Other names registered for the same object, which the coverage test must also account for.
    aliases: tuple[str, ...] = ()
    section: str = ''

    def __post_init__(self):
        assert self.kind in KINDS, f"{self.name}: unknown kind {self.kind!r}"
        assert self.env in (MARKDOWN, STATIC, META), f"{self.name}: unknown env {self.env!r}"
        assert bool(self.example) == bool(self.expect), \
            f"{self.name}: an example and its output come as a pair"

    @property
    def names(self) -> tuple[str, ...]:
        """Every name this entry accounts for: itself, its aliases, and its precision family."""
        base = (self.name, *self.aliases)
        if not self.precisions:
            return base
        return base + tuple(f'{name}{digit}' for name in base for digit in PRECISIONS)

    @property
    def display(self) -> str:
        """How the name is written at a call site: `|disp`, `PQ(...)`, `.eq`, `values:`."""
        match self.kind:
            case 'filter' | 'jinja-builtin':
                return f'|{self.name}'
            case 'attribute':
                return f'.{self.name}'
            case 'meta-key' | 'values-key':
                return f'{self.name}:'
            case 'namespace':
                return f'{self.name}.'
            case _:
                return self.name


def example_context() -> dict:
    """
    The one context every example in the table is rendered in.

    Small on purpose and printed at the head of the document, so an example reads on its own.
    The quantities are chosen to exercise the distinctions that actually catch people out: `v` is
    a given and therefore exact, `c_s` is measured and so `eq` writes `\\approx` for it, and
    `result`/`result_approx` are the pair an `answer-interval.md` spans.
    """
    from core.builder.context.quantities import (
        PhysicsConstant,
        PhysicsQuantity,
        QuantityList,
        QuantityProduct,
    )
    from core.builder.context.quantities.math import MathObject

    build = PhysicsQuantity.construct
    return {
        # A given: exact, because a statement that says 3 m/s is not approximately anything.
        'v': build(3, 'm/s', symbol='v'),
        'm': build(1.5, 'kg', symbol='m'),
        'rho': build(1000, 'kg/m^3', symbol=r'\rho'),
        'E': build(1.602176634e-19, 'J', symbol='E'),
        'd': build(5, 'km', symbol='d'),
        # Small enough that `g` still writes it out in full -- which is the case `e` exists for.
        'frac': build(1.00356e-4, '1', symbol='w'),
        'alpha': build(44.15, 'degree', symbol=r'\alpha'),
        # Measured, and shown to three figures: the shape of a `constants.yaml` entry.
        'c_s': PhysicsConstant.construct('speed_sound', magnitude=343, unit='m/s',
                                         symbol='c_s', exact=False, digits=3),
        # The pair an answer interval spans -- the exact constant and the sheet's rounding of it.
        'result': build(64.5663, 'day', symbol='t'),
        'result_approx': build(64.5665, 'day', symbol='t'),
        'sides': QuantityList(build(1, 'm'), build(2, 'm'), build(3, 'm')),
        'box': QuantityProduct(build(3, 'cm'), build(4, 'cm'), build(5, 'cm')),
        'eq': {
            'kin': MathObject('demo:kin', r'E_\text{kin} = \frac{1}{2} m v^2'),
            'chain': MathObject('demo:chain', 'a &= b \\\\\n&= c'),
            'sys': MathObject('demo:sys', 'x &+& y &=& 1 \\\\\nx &-& y &=& 0'),
        },
        # `const` as the context builds it: a namespace of measured constants, each carrying the
        # `digits:` the sheet prints it to, which is what `.approx` rounds to.
        'const': {
            'g': PhysicsConstant.construct('g', magnitude=9.80665, unit='m/s^2',
                                           symbol='g', exact=False, digits=2),
        },
        'words': {'air': 'vzduch'},
        'blocks': {'setup': 'set xlabel "t"\nset ylabel "v"'},
    }


def static_example_context() -> dict:
    """The same for `StaticRenderer`, whose vocabulary is about people and numbering."""
    import datetime
    return {
        'n': 3,
        'people': [{'name': 'Jana Nováková', 'gender': 'f'}],
        'team': ['Jana Nováková', 'Peter Novák', 'Eva Horváthová'],
        'date': datetime.date(2025, 10, 2),
    }


def render_example(entry: Entry) -> str:
    """
    What `entry.example` actually produces, through the environment the entry belongs to.

    The real renderer, not a stub: an example that passes here is one an author can paste.
    """
    from core.builder.jinja import MarkdownJinjaRenderer

    if entry.env == STATIC:
        return _render_static(entry.example)
    return MarkdownJinjaRenderer().render(entry.example, example_context())


def _render_static(template: str) -> str:
    """
    `StaticRenderer` loads from a directory, so an in-memory example needs one made for it.

    Cheaper than it looks and done once per example; the alternative is a second renderer class
    that exists only for this file.
    """
    import tempfile

    from core.builder.jinja import StaticRenderer

    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / 'example.jtex'
        path.write_text(template)
        return StaticRenderer(directory).render(path, static_example_context())


#: Every name an author may write, in the order the document prints them.
#:
#: The `expect` beside each example is not decoration: `test_reference.py` renders the example and
#: compares. Change a filter's output and this file goes red with it.
_FILTERS: tuple[Entry, ...] = (

    # ------------------------------------------------------------------ numbers
    Entry('f', 'filter', precisions=True, section='Numbers',
          summary='Fixed notation. The digit is decimal places; bare `|f` prints what the value '
                  'has.',
          note='A quantity comes back as a complete `\\qty{}{}`, so do not wrap it in `\\num{}` '
               'yourself.',
          example='(§ v|f2 §)', expect='\\qty{3.00}{\\metre\\per\\second}'),
    Entry('g', 'filter', precisions=True, section='Numbers',
          summary="Python's `g`: significant figures, and an exponent only when the number is "
                  'small or large enough to need one.',
          example='(§ E|g4 §)', expect='\\qty{1.602e-19}{\\joule}'),
    Entry('e', 'filter', precisions=True, section='Numbers',
          summary='Scientific notation, always. The digit is decimals after the point, as '
                  "Python's `e` counts them.",
          note='`|g` only reaches for an exponent below `1e-5`, so `1.004e-4` comes back from it '
               'as `0.0001004`. This is the family for a value the booklet prints as a power of '
               'ten. **It shadows Jinja\'s own `|e`** (an alias for `escape`), which is harmless '
               'here because the environment sets `autoescape=False`.',
          example='(§ frac|g §) versus (§ frac|e3 §)', expect='\\num{0.000100356} versus \\num{1.004e-04}'),
    Entry('n', 'filter', section='Numbers',
          signature='|n',
          summary=r'Wrap in siunitx `\num{}`, as-is.',
          note='Idempotent: a quantity already renders as `\\num{…}` or `\\qty{…}{…}`, and this '
               'leaves such a value alone rather than producing `\\num{\\num{…}}`, which siunitx '
               'cannot parse.',
          example='(§ 0.0072|n §)', expect='\\num{0.0072}'),
    Entry('nf', 'filter', precisions=True, section='Numbers',
          summary=r'`\num{}` around a fixed-notation number. Idempotent, like `|n`.',
          example='(§ 0.0072|nf3 §)', expect='\\num{0.007}'),
    Entry('ng', 'filter', precisions=True, section='Numbers',
          summary=r'`\num{}` around a `g`-formatted number.',
          example='(§ 1234.5|ng3 §)', expect='\\num{1.23e+03}'),
    Entry('ne', 'filter', precisions=True, section='Numbers',
          summary=r'`\num{}` around a number in scientific notation.',
          example='(§ 0.0072|ne2 §)', expect='\\num{7.20e-03}'),

    # -------------------------------------------------- a value with its symbol
    Entry('ef', 'filter', precisions=True, section='A value with its symbol',
          summary=r'`<symbol> = <value>`, the value in fixed notation.',
          note='The symbol comes from the quantity -- `symbol:` on a `values:` entry, `.alias()` '
               'on a `derived:` one -- so the source writes one tag and not `$v = (§ v §)$`. A '
               'quantity with no symbol raises rather than printing a gap.',
          example='$(§ v|ef1 §)$', expect='$v = \\qty{3.0}{\\metre\\per\\second}$'),
    Entry('eg', 'filter', precisions=True, section='A value with its symbol',
          summary=r'The same with a `g`-formatted value.',
          example='$(§ E|eg3 §)$', expect='$E = \\qty{1.6e-19}{\\joule}$'),
    Entry('ee', 'filter', precisions=True, section='A value with its symbol',
          summary=r'The same with the value in scientific notation.',
          example='$(§ E|ee2 §)$', expect='$E = \\qty{1.60e-19}{\\joule}$'),
    Entry('af', 'filter', precisions=True, section='A value with its symbol',
          summary=r'`<symbol> \approx <value>`, the value in fixed notation.',
          note='**Which of `|ef` and `|af` is a question about the value, not about the source.** '
               'A given declared as exactly 2 g prints `2` at `|f0` and `2` in full, so nothing '
               'was rounded and `=` stands; `|af` there would assert an approximation nobody '
               'made. Where the value *does* decide for itself, write `(§ x.eq §)` and let it.',
          example='$(§ result|af(3) §)$', expect='$t \\approx \\qty{64.566}{\\day}$'),
    Entry('ag', 'filter', precisions=True, section='A value with its symbol',
          summary=r'The same with a `g`-formatted value.',
          example='$(§ c_s|ag3 §)$', expect='$c_s \\approx \\qty{343}{\\metre\\per\\second}$'),
    Entry('ae', 'filter', precisions=True, section='A value with its symbol',
          summary=r'The same with the value in scientific notation.',
          example='$(§ E|ae2 §)$', expect='$E \\approx \\qty{1.60e-19}{\\joule}$'),

    # ------------------------------------------------------------- plain text
    Entry('txt', 'filter', precisions=True, section='Plain text, where there is no TeX',
          summary='The value written out as text -- `3 m/s`, `1000 kg/m³`, `45°` -- in fixed '
                  'notation.',
          note='**For an `.svg` and a `.gp` axis label, and nowhere else.** Those are put on the '
               'page by `rsvg-convert` and gnuplot, which are not TeX, so a `\\qty{}{}` there '
               'prints its own backslashes. In Markdown, in a `.tikz`, in an `eq:` entry, '
               'siunitx is better at this than any string can be. The unit comes from pint\'s '
               'own `~P` spec, so a unit that can be computed can be printed.',
          example='(§ rho|txt §)', expect='1000 kg/m³'),
    Entry('txtg', 'filter', precisions=True, section='Plain text, where there is no TeX',
          summary="The same with the magnitude in Python's `g`, and an exponent written "
                  '`6.674×10⁻¹¹`.',
          note='Worth having rather than leaving to `txt`: fixed notation writes the '
               'gravitational constant as `0.00000000006674`, which is not a label anybody can '
               'read at 7pt.',
          example='(§ E|txtg4 §)', expect='1.602×10⁻¹⁹ J'),

    # ------------------------------------------------------------- quantities
    Entry('mag', 'filter', section='Quantities',
          signature='|mag',
          summary='The bare magnitude as a number, with no unit and no siunitx call.',
          note='A float, not a quantity -- so it is what to reach for when the number has to go '
               'into arithmetic a template does, or into a gnuplot script as a literal.',
          example='(§ v|mag §)', expect='3'),
    Entry('unit', 'filter', section='Quantities',
          signature='|unit',
          summary=r'The unit alone, as siunitx `\unit{…}`, with the magnitude dropped.',
          example='(§ rho|unit §)', expect='\\unit{\\kilo\\gram\\per\\metre\\cubed}'),
    Entry('sim', 'filter', section='Quantities',
          signature='|sim',
          summary='Converted to base SI units.',
          example='(§ d|sim §)', expect='\\qty{5000}{\\metre}'),
    Entry('snap', 'filter', section='Quantities',
          signature='|snap(quantum)',
          summary='Round a range outward onto a grid of `quantum`, where the format spec cannot.',
          note='`__format__` already moves each end outward to the last place it prints, which is '
               'what keeps a printed band from rejecting a correct answer. This is the same '
               'operation with the grid chosen rather than inferred, because `.0f` is the coarsest a '
               'format spec offers and an answer may be good to less -- one good to four figures in '
               'kilometres wants a grid of ten. **Not `widen`:** it moves each end to the next grid '
               'point and no further, and snapping an already-snapped range is a no-op.',
          example='(§ (result % result_approx)|snap(0.5)|f1 §)', expect='\\qtyrange{64.5}{65.0}{\\day}'),
    Entry('dms', 'filter', section='Quantities',
          signature='|dms(places=3)',
          summary=r'An angle as siunitx `\ang{d;m;s}` -- degrees, arcminutes, arcseconds.',
          note='`places` chooses how far to go: 1 degrees, 2 degrees and minutes, 3 with '
               'seconds. The rounding happens once, in the smallest place, and carries upward. '
               'It is the same number as the decimal form, so it belongs in `answer-also.md` '
               'rather than replacing it.',
          example='$(§ alpha|dms(2) §)$', expect='$\\ang{44;9;}$'),

    # ------------------------------------------------------------------ maths
    Entry('raw', 'filter', section='Maths',
          signature='|raw',
          summary='The fragment with no delimiters at all. This is what a bare `(§ eq.x §)` '
                  'already does, so the filter exists to say so.',
          note='Raw is the default because wrapping a bare fragment is one filter away, while '
               'unwrapping a pre-wrapped one is not possible in a template at all. It is what '
               'lets one equation be spliced into another.',
          example='(§ eq.kin|raw §)', expect='E_\\text{kin} = \\frac{1}{2} m v^2'),
    Entry('inl', 'filter', section='Maths',
          signature='|inl',
          summary='Inline maths: `$…$`.',
          note='Never write `$(§ eq.x §)$` by hand -- that is this filter, spelled longer. Put '
               'any sentence punctuation outside the maths.',
          example='(§ eq.kin|inl §)', expect='$E_\\text{kin} = \\frac{1}{2} m v^2$'),
    Entry('disp', 'filter', section='Maths',
          signature="|disp, |disp('.')",
          summary='A display block with its `{#eq:…}` label, optionally with trailing '
                  'punctuation inside the maths.',
          note='The label is the `eq:` key, so renaming the key renames the reference. **Whether '
               'the label is emitted is not yours to choose**: the renderer sets it from the file '
               "being rendered, against the module's `equation_numbering`, because a problem "
               'statement never numbers its equations. That is what lets one `eq:` entry serve '
               'both the statement and the solution. Inside a list item, chain '
               "`|indent(4)`.",
          example="(§ eq.kin|disp('.') §)", expect='$$\n'
                                            '    E_\\text{kin} = \\frac{1}{2} m v^2.\n'
                                            '$$ {#eq:demo:kin}'),
    Entry('dispd', 'filter', section='Maths', signature='|dispd',
          summary="Shorthand for `|disp('.')`.",
          example='(§ eq.kin|dispd §)', expect='$$\n'
                                        '    E_\\text{kin} = \\frac{1}{2} m v^2.\n'
                                        '$$ {#eq:demo:kin}'),
    Entry('dispc', 'filter', section='Maths', signature='|dispc',
          summary="Shorthand for `|disp(',')`.",
          example='(§ eq.kin|dispc §)', expect='$$\n'
                                        '    E_\\text{kin} = \\frac{1}{2} m v^2,\n'
                                        '$$ {#eq:demo:kin}'),
    Entry('disps', 'filter', section='Maths', signature='|disps',
          summary="Shorthand for `|disp(';')`.",
          example='(§ eq.kin|disps §)', expect='$$\n'
                                        '    E_\\text{kin} = \\frac{1}{2} m v^2;\n'
                                        '$$ {#eq:demo:kin}'),
    Entry('dispq', 'filter', section='Maths', signature='|dispq',
          summary="Shorthand for `|disp('?')`.",
          example='(§ eq.kin|dispq §)', expect='$$\n'
                                        '    E_\\text{kin} = \\frac{1}{2} m v^2?\n'
                                        '$$ {#eq:demo:kin}'),
    Entry('dispe', 'filter', section='Maths', signature='|dispe',
          summary="Shorthand for `|disp('!')`.",
          example='(§ eq.kin|dispe §)', expect='$$\n'
                                        '    E_\\text{kin} = \\frac{1}{2} m v^2!\n'
                                        '$$ {#eq:demo:kin}'),
    Entry('align', 'filter', section='Maths',
          signature="|align, |align('.')",
          summary='A display block wrapping the fragment in `aligned`, for a chain aligned on a '
                  'single relation.',
          note='`aligned` pairs its columns `rl rl rl`, so it is right for a chain with a single '
               'relation and for a grid of independent equations, and **wrong for a chain of two or '
               'more relations in one row** -- that is `|arr`.',
          example="(§ eq.chain|align('.') §)", expect='$$\n'
                                               '    \\begin{aligned}\n'
                                               '        a &= b \\\\\n'
                                               '        &= c.\n'
                                               '    \\end{aligned}\n'
                                               '$$ {#eq:demo:chain}'),
    Entry('alignd', 'filter', section='Maths', signature='|alignd',
          summary="Shorthand for `|align('.')`.",
          example='(§ eq.chain|alignd §)', expect='$$\n'
                                           '    \\begin{aligned}\n'
                                           '        a &= b \\\\\n'
                                           '        &= c.\n'
                                           '    \\end{aligned}\n'
                                           '$$ {#eq:demo:chain}'),
    Entry('alignc', 'filter', section='Maths', signature='|alignc',
          summary="Shorthand for `|align(',')`.",
          example='(§ eq.chain|alignc §)', expect='$$\n'
                                           '    \\begin{aligned}\n'
                                           '        a &= b \\\\\n'
                                           '        &= c,\n'
                                           '    \\end{aligned}\n'
                                           '$$ {#eq:demo:chain}'),
    Entry('aligns', 'filter', section='Maths', signature='|aligns',
          summary="Shorthand for `|align(';')`.",
          example='(§ eq.chain|aligns §)', expect='$$\n'
                                           '    \\begin{aligned}\n'
                                           '        a &= b \\\\\n'
                                           '        &= c;\n'
                                           '    \\end{aligned}\n'
                                           '$$ {#eq:demo:chain}'),
    Entry('alignq', 'filter', section='Maths', signature='|alignq',
          summary="Shorthand for `|align('?')`.",
          example='(§ eq.chain|alignq §)', expect='$$\n'
                                           '    \\begin{aligned}\n'
                                           '        a &= b \\\\\n'
                                           '        &= c?\n'
                                           '    \\end{aligned}\n'
                                           '$$ {#eq:demo:chain}'),
    Entry('aligne', 'filter', section='Maths', signature='|aligne',
          summary="Shorthand for `|align('!')`.",
          example='(§ eq.chain|aligne §)', expect='$$\n'
                                           '    \\begin{aligned}\n'
                                           '        a &= b \\\\\n'
                                           '        &= c!\n'
                                           '    \\end{aligned}\n'
                                           '$$ {#eq:demo:chain}'),
    Entry('arr', 'filter', section='Maths',
          signature="|arr('rclcl'), |arr('rclcl', '.')",
          summary='A display block wrapping the fragment in `array`, for a display where more '
                  'than one column has to line up. **The column spec is required.**',
          note='An array has no sensible default layout, hence the argument. It does three things '
               'for you, all of them `array` defects: every column is put in display style, so a '
               '`\\frac` does not shrink; the terminal punctuation lands inside the final cell '
               'rather than floating at the array\'s vertical centre; and every row separator '
               'gets `\\jot` of glue, because `array` zeroes the lengths `\\openup` would raise.',
          example="(§ eq.sys|arr('rcrcl', '.') §)", expect='$$\n'
                                                    '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                    '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                    '        x &-& y &=& 0.\n'
                                                    '    \\end{array}\n'
                                                    '$$ {#eq:demo:sys}'),
    Entry('arrd', 'filter', section='Maths', signature="|arrd('rclcl')",
          summary="Shorthand for `|arr(columns, '.')`.",
          example="(§ eq.sys|arrd('rcrcl') §)", expect='$$\n'
                                                '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                '        x &-& y &=& 0.\n'
                                                '    \\end{array}\n'
                                                '$$ {#eq:demo:sys}'),
    Entry('arrc', 'filter', section='Maths', signature="|arrc('rclcl')",
          summary="Shorthand for `|arr(columns, ',')`.",
          example="(§ eq.sys|arrc('rcrcl') §)", expect='$$\n'
                                                '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                '        x &-& y &=& 0,\n'
                                                '    \\end{array}\n'
                                                '$$ {#eq:demo:sys}'),
    Entry('arrs', 'filter', section='Maths', signature="|arrs('rclcl')",
          summary="Shorthand for `|arr(columns, ';')`.",
          example="(§ eq.sys|arrs('rcrcl') §)", expect='$$\n'
                                                '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                '        x &-& y &=& 0;\n'
                                                '    \\end{array}\n'
                                                '$$ {#eq:demo:sys}'),
    Entry('arrq', 'filter', section='Maths', signature="|arrq('rclcl')",
          summary="Shorthand for `|arr(columns, '?')`.",
          example="(§ eq.sys|arrq('rcrcl') §)", expect='$$\n'
                                                '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                '        x &-& y &=& 0?\n'
                                                '    \\end{array}\n'
                                                '$$ {#eq:demo:sys}'),
    Entry('arre', 'filter', section='Maths', signature="|arre('rclcl')",
          summary="Shorthand for `|arr(columns, '!')`.",
          example="(§ eq.sys|arre('rcrcl') §)", expect='$$\n'
                                                '    \\begin{array}{>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}r>{\\displaystyle}c>{\\displaystyle}l}\n'
                                                '        x &+& y &=& 1 \\\\[\\jot]\n'
                                                '        x &-& y &=& 0!\n'
                                                '    \\end{array}\n'
                                                '$$ {#eq:demo:sys}'),

    # ------------------------------------------------------------------ words
    Entry('q', 'filter', section='Words inside maths',
          signature='|q',
          summary=r'Wrap a word in `\QText{}` -- `\quad\text{…}\quad`.',
          note='For a conjunction joining two terms inside one display. The whole tag is '
               "`(§ i18n.andw|q §)`.",
          example='$a (§ words.air|q §) b$', expect='$a \\QText{vzduch} b$'),
    Entry('qq', 'filter', section='Words inside maths',
          signature='|qq',
          summary=r'The same with `\QQText{}` -- the wider of the two, for a word joining two '
                  'whole equations.',
          example='$a (§ words.air|qq §) b$', expect='$a \\QQText{vzduch} b$'),
)


_GLOBALS: tuple[Entry, ...] = (

    # ------------------------------------------------- building a quantity
    Entry('PQ', 'global', section='Building a quantity',
          signature="PQ(magnitude, unit, symbol=None)",
          summary='Build a quantity inside an expression.',
          note='`values:` is where a quantity a *statement gives* belongs; this is for one a '
               '`derived:` expression needs on the spot, and for the odd literal in a template.',
          example="(§ PQ(9.81, 'm/s^2', symbol='g')|ef2 §)", expect='g = \\qty{9.81}{\\metre\\per\\second\\squared}'),
    Entry('QL', 'global', aliases=('QuantityList',), section='Building a quantity',
          signature='QL(q1, q2, ...)  ·  QuantityList(...)',
          summary='Several commensurate quantities printed as a list: `1 m, 2 m, 3 m`.',
          note='Every element is coerced to the first one\'s unit on construction, and the unit '
               'is repeated on each -- `list-units = repeat` in `core/latex/siunitx.tex`. '
               'Indexable and iterable.',
          example='(§ sides|f0 §)', expect='\\qtylist{1;2;3}{\\metre}'),
    Entry('QP', 'global', aliases=('QuantityProduct',), section='Building a quantity',
          signature='QP(q1, q2, ...)  ·  QuantityProduct(...)',
          summary='The same printed as a product -- the dimensions of a box, `3 cm × 4 cm × 5 cm`.',
          example='(§ box|f0 §)', expect='\\qtyproduct{3 x 4 x 5}{\\centi\\metre}'),
    Entry('QR', 'global', aliases=('QuantityRange',), section='Building a quantity',
          signature='QR(minimum, maximum)  ·  QuantityRange(...)',
          summary='A span of two commensurate quantities. **Usually written as the `%` operator '
                  'rather than by name** -- see below.',
          note='A range here is the set of answers a marker accepts, so `__format__` rounds each end '
               '**outward** to the last place it prints: the minimum floored, the maximum ceiled. '
               'Rounding to nearest would shrink the set and turn away correct work. `|snap(q)` '
               'chooses the grid where the format spec cannot. `QR` refuses a reversed range, which '
               'is why the smaller endpoint is written first.',
          example='(§ QR(result, result_approx)|f3 §)', expect='\\qtyrange{64.566}{64.567}{\\day}'),
    Entry('%', 'operator', section='Building a quantity',
          signature='(a % b)',
          summary='Builds a `QuantityRange` from two quantities. This is how an answer interval is '
                  'written; `QR` is never spelled out.',
          note='An `answer-interval.md` is one tag: `$(§ (result % result_approx)|f2 §)$`. Smaller '
               'endpoint first -- `%` refuses a reversed range, which is the whole reason the '
               '`derived:` pair is named `result` and `result_approx` that way round and not the '
               'other.',
          example='(§ (result % result_approx)|f3 §)', expect='\\qtyrange{64.566}{64.567}{\\day}'),

    # ---------------------------------------------------- including a file
    Entry('include', 'global', section='Including a file',
          signature="include('vetranie.py')",
          summary='The contents of a file beside the template, verbatim -- so a code listing '
                  '*is* the runnable program rather than a second copy of it that goes stale.',
          note='The path is relative to the file the tag is written in. Inside a list item, '
               "chain `|indent(4)`. Like `blocks:`, the text comes back as written and the "
               'second pass expands it, so an included file may itself carry tags; unlike '
               '`blocks:`, a missing file **raises** rather than resolving to nothing, because an '
               'empty code block compiles perfectly and prints nothing. Write it inside a fence, '
               'and it is highlighted like any other fenced block.'),

    # ------------------------------------------------------------ mathematics
    Entry('sqrt', 'global', section='Mathematics',
          signature='sqrt(x)',
          summary='A square root, as `x ** 0.5` -- so it halves the unit too and a quantity '
                  'comes back a quantity.',
          example="(§ sqrt(PQ(2, 'm^2'))|f4 §)", expect='\\qty{1.4142}{\\metre}'),
    Entry('cbrt', 'global', section='Mathematics', signature='cbrt(x)',
          summary='A cube root, unit-aware the way `sqrt` is: the unit\'s exponents divide by '
                  'three, so a volume in `m^3` comes back in `m`.',
          note='It was `np.cbrt`, which does not know what a unit is -- and on a quantity it did '
               'not drop the unit but raised, so the global was usable on a bare number and on '
               'nothing else. A unit that is not a cube keeps an honest fractional power rather '
               'than being rounded off: `cbrt(PQ(8, \'litre\'))` is `2 l^{0.333}`.',
          example='(§ cbrt(PQ(27, \'metre**3\')) §)', expect='\\qty{3}{\\metre}'),
    Entry('pow', 'global', section='Mathematics', signature='pow(x, y)',
          summary='`x` to the power `y`. Jinja has `**` too; this is for when a filter chain '
                  'reads better.',
          example='(§ pow(2, 10)|f0 §)', expect='1024'),
    Entry('exp', 'global', section='Mathematics', signature='exp(x)',
          summary="Euler's number to the power `x`.",
          example='(§ exp(1)|f4 §)', expect='2.7183'),
    Entry('log', 'global', section='Mathematics', signature='log(x)',
          summary='The **natural** logarithm. `log10` and `log2` are the other two.',
          example='(§ log(euler)|f0 §)', expect='1'),
    Entry('log10', 'global', section='Mathematics', signature='log10(x)',
          summary='Base-ten logarithm.',
          example='(§ log10(1000)|f0 §)', expect='3'),
    Entry('log2', 'global', section='Mathematics', signature='log2(x)',
          summary='Base-two logarithm.',
          example='(§ log2(1024)|f0 §)', expect='10'),
    Entry('sin', 'global', section='Mathematics', signature='sin(x)',
          summary='Sine. **Radians** -- wrap a degree figure in `rad()`.',
          example='(§ sin(rad(30))|f3 §)', expect='0.500'),
    Entry('cos', 'global', section='Mathematics', signature='cos(x)', summary='Cosine, in radians.',
          example='(§ cos(0)|f0 §)', expect='1'),
    Entry('tan', 'global', section='Mathematics', signature='tan(x)', summary='Tangent, in radians.',
          example='(§ tan(rad(45))|f3 §)', expect='1.000'),
    Entry('asin', 'global', section='Mathematics', signature='asin(x)',
          summary='Inverse sine, returning radians.',
          example='(§ deg(asin(0.5))|f0 §)', expect='30'),
    Entry('acos', 'global', section='Mathematics', signature='acos(x)',
          summary='Inverse cosine, returning radians.',
          example='(§ deg(acos(0.5))|f0 §)', expect='60'),
    Entry('atan', 'global', section='Mathematics', signature='atan(x)',
          summary='Inverse tangent, returning radians.',
          example='(§ deg(atan(1))|f0 §)', expect='45'),
    Entry('atan2', 'global', section='Mathematics', signature='atan2(y, x)',
          summary='The two-argument inverse tangent, which gets the quadrant right. `y` first.',
          example='(§ deg(atan2(1, -1))|f0 §)', expect='135'),
    Entry('rad', 'global', section='Mathematics', signature='rad(degrees)',
          summary='Degrees to radians, on a bare number.',
          example='(§ rad(180)|f4 §)', expect='3.1416'),
    Entry('deg', 'global', section='Mathematics', signature='deg(radians)',
          summary='Radians to degrees, on a bare number.',
          note='For a *quantity* carrying an angle unit, `|f`/`.to()` already know what to do; '
               'this is the bare-number pair to `rad`.',
          example='(§ deg(pi)|f0 §)', expect='180'),
    Entry('ceil', 'global', section='Mathematics', signature='ceil(x)',
          summary='Round up. **Unit-aware**: a quantity comes back a quantity, a number a number.',
          note='`ceil`, `floor` and `round` each dispatch on the operand, which is why a tag may '
               'write `ceil(n)` without knowing whether `n` came from `values:` or from '
               'arithmetic.',
          example="(§ ceil(PQ(2.1, 'm'))|f0 §)", expect='\\qty{3}{\\metre}'),
    Entry('floor', 'global', section='Mathematics', signature='floor(x)',
          summary='Round down, unit-aware.',
          example="(§ floor(PQ(2.9, 'm'))|f0 §)", expect='\\qty{2}{\\metre}'),
    Entry('round', 'global', section='Mathematics', signature='round(x)',
          summary='Round to nearest, unit-aware. Takes **no** precision -- that is what `|f2` is '
                  'for.',
          note="**Half-to-even**, because it is numpy's: `round(2.5)` is 2 and `round(3.5)` is "
               '4. Where that matters, say which way you meant with `ceil` or `floor`.',
          example="(§ round(PQ(2.5, 'm'))|f0 §)", expect='\\qty{2}{\\metre}'),
    Entry('gamma', 'global', section='Mathematics', signature='gamma(x)',
          summary="The gamma function, `math.gamma`.",
          example='(§ gamma(5)|f0 §)', expect='24'),
    Entry('beta', 'global', section='Mathematics', signature='beta(x, y)',
          summary='The beta function, built from three gammas.',
          example='(§ beta(2, 3)|g3 §)', expect='0.0833'),
    Entry('pi', 'global', section='Mathematics', signature='pi',
          summary='π, as a plain float.',
          example='(§ pi|f5 §)', expect='3.14159'),
    Entry('tau', 'global', section='Mathematics', signature='tau',
          summary='τ = 2π.',
          example='(§ tau|f5 §)', expect='6.28319'),
    Entry('euler', 'global', section='Mathematics', signature='euler',
          summary="e, Euler's number. Spelled out because `e` is already a filter.",
          example='(§ euler|f5 §)', expect='2.71828'),
)


_ATTRIBUTES: tuple[Entry, ...] = (

    Entry('eq', 'attribute', aliases=('equals',), section='Attributes of a quantity',
          signature='.eq  ·  .equals',
          summary='`<symbol> = <value>` or `<symbol> \\approx <value>`, **the quantity deciding '
                  'which**.',
          note='Two independent tests, because each catches what the other cannot. The value has '
               'to be the true one -- `const.speed_sound` is 343 m/s, which prints back perfectly '
               'and is still not the speed of sound, and only the declaration knows that -- '
               '**and** the figures it prints have to be all of it: `sqrt(2)` is exact by every '
               'declaration on its way there and prints as 1.41421, and only the arithmetic knows '
               'that. `exact` defaults to true, because a number a statement *gives* is exact.',
          example='$(§ v.eq §)$ and $(§ c_s.eq §)$', expect='$v = \\qty{3}{\\metre\\per\\second}$ and $c_s \\approx \\qty{343}{\\metre\\per\\second}$'),
    Entry('apx', 'attribute', aliases=('approximately',), section='Attributes of a quantity',
          signature='.apx  ·  .approximately',
          summary=r'`<symbol> \approx <value>` outright, at the quantity\'s `digits:` figures '
                  "rather than `%g`'s six.",
          note='`eq` reaches for `\\approx` where the value has earned it; this says so whatever '
               'the value thinks. `eq` prints what it has, `apx` says "to this many figures".',
          example='$(§ c_s.apx §)$', expect='$c_s \\approx \\qty{343}{\\metre\\per\\second}$'),
    Entry('mag', 'attribute', section='Attributes of a quantity',
          signature='.mag',
          summary='The bare magnitude as a float, with no unit and no siunitx call.',
          note='A float, not a quantity -- so `.mag` is what a gnuplot script or a `.svg` wants '
               'as a literal, and what arithmetic inside a template wants.',
          example='(§ v.mag §)', expect='3'),
    Entry('unit', 'attribute', section='Attributes of a quantity',
          signature='.unit',
          summary="The pint unit object. For the printed unit, use the `|unit` filter.",
          example='(§ rho.unit §)', expect='kilogram / meter ** 3'),
    Entry('s', 'attribute', aliases=('sym', 'symbol'), section='Attributes of a quantity',
          signature='.s  ·  .sym  ·  .symbol',
          summary='The declared symbol, as LaTeX, with no value beside it.',
          note='**A symbol is declared on the quantity, not written beside it** -- `symbol:` on a '
               '`values:` entry, `.alias()` on a `derived:` one. That is what lets `$(§ x.eq §)$` '
               'be one tag rather than `$\\rho = (§ rho §)$`.',
          example='$(§ rho.s §)$', expect='$\\rho$'),
    Entry('full', 'attribute', section='Attributes of a quantity',
          signature='.full',
          summary='The value and unit at full precision, with no symbol and no relation.',
          example='(§ c_s.full §)', expect='\\qty{343}{\\metre\\per\\second}'),
    Entry('to', 'attribute', section='Attributes of a quantity',
          signature=".to('cm')",
          summary='Converted to a commensurate unit. Carries the symbol, `digits` and `exact` '
                  'across.',
          note='Usually the last thing a `derived:` expression does, because the unit a result '
               'should print in is rarely the one the arithmetic produced.',
          example="(§ d.to('m')|f0 §)", expect='\\qty{5000}{\\metre}'),
    Entry('alias', 'attribute', section='Attributes of a quantity',
          signature=".alias('\\\\rho')",
          summary='The same quantity carrying a symbol. This is how a `derived:` entry declares '
                  'one.',
          note='**Four backslashes in a double-quoted YAML scalar**, two in a single-quoted one. '
               'Takes no precision -- digits are declared or they are absent.',
          example="(§ (m / PQ(1, 'm^3')).alias('\\\\rho').eq §)", expect='\\rho = \\qty{1.5}{\\kilo\\gram\\per\\metre\\cubed}'),
    Entry('simplify', 'attribute', section='Attributes of a quantity',
          signature='.simplify()',
          summary='Converted to base SI units. The `|sim` filter is the same thing.',
          example='(§ d.simplify()|f0 §)', expect='\\qty{5000}{\\metre}'),
    Entry('only_unit', 'attribute', section='Attributes of a quantity',
          signature='.only_unit()',
          summary=r'The unit alone as `\unit{…}`. The `|unit` filter is the same thing.',
          example='(§ rho.only_unit() §)', expect='\\unit{\\kilo\\gram\\per\\metre\\cubed}'),
    Entry('approx', 'attribute', section='Attributes of a quantity',
          signature='.approx',
          summary='**On a `const.` value only:** the constant rounded to the figures the '
                  'constants sheet prints.',
          note='This is the second of the two admissible values of every constant, and the reason '
               'an answer interval is a span at all: the competitor is holding the sheet, so both '
               "that rounding and `constants.yaml`'s own figure are legitimate arithmetic. A "
               '`derived:` pair is `result` computed with `const.g` and `result_approx` with '
               '`const.g.approx`.',
          example='(§ c_s.approx.eq §)', expect='c_s \\approx \\qty{343}{\\metre\\per\\second}'),
    Entry('exact', 'attribute', section='Attributes of a quantity',
          signature='.exact',
          summary='Whether the value is the true one. Spreads through arithmetic as '
                  '**contamination only** -- `a * b` is exact only if both are -- and never as a '
                  'guarantee.',
          example='(§ v.exact §) then (§ c_s.exact §)', expect='True then False'),
    Entry('digits', 'attribute', section='Attributes of a quantity',
          signature='.digits',
          summary='How many figures to **print**, or `None`. Presentation, not uncertainty.',
          note='It does **not** propagate through arithmetic. A constant shown to one figure because '
               'that is what the constants sheet prints would, if it propagated, claim that '
               'precision for everything computed from it, and an answer of 24.6 mm would print as '
               '20. It travels only where the quantity does: `to`, `alias`, `simplify`, '
               '`approximate`, and a sign.',
          example='(§ c_s.digits §)', expect='3'),
    Entry('printed_digits', 'attribute', section='Attributes of a quantity',
          signature='.printed_digits',
          summary='`digits` if it is declared, and the default otherwise -- so it is always a '
                  'number.',
          example='(§ v.printed_digits §)', expect='3'),
    Entry('prints_exactly', 'attribute', section='Attributes of a quantity',
          signature='.prints_exactly',
          summary=r'Whether `.eq` may write `=`: exact **and** round-tripping through its own '
                  'printed form.',
          note='The round-trip allows a thousand ulps rather than demanding equality. A value that '
               'is exactly 0.1 by construction can still be stored a few ulps out -- after solving a '
               'linear system, say -- and an equality test would call it rounded; a value that '
               'really was rounded is wrong by nine orders of magnitude more than that, so the '
               'threshold is not a tuned number.',
          example='(§ v.prints_exactly §) then (§ c_s.prints_exactly §)', expect='True then False'),
    Entry('minimum', 'attribute', section='Attributes of a range, list or product',
          signature='.minimum',
          summary='A range\'s lower endpoint, as a quantity.',
          example='(§ (result % result_approx).minimum|f3 §)', expect='\\qty{64.566}{\\day}'),
    Entry('maximum', 'attribute', section='Attributes of a range, list or product',
          signature='.maximum',
          summary="A range's upper endpoint.",
          example='(§ (result % result_approx).maximum|f3 §)', expect='\\qty{64.567}{\\day}'),
    Entry('qs', 'attribute', section='Attributes of a range, list or product',
          signature='.qs',
          summary='The elements of a `QL` or a `QP`, as a plain list. They are also indexable and '
                  'iterable directly.',
          example='(§ sides.qs[1]|f0 §)', expect='\\qty{2}{\\metre}'),
)


#: `StaticRenderer` serves the `.jtex` templates, and its vocabulary is **disjoint** from the
#: Markdown one above: these eight filters and four globals exist there and nowhere else, and
#: none of the 182 Markdown filters exists here. A `.jtex` also writes its variables `(* x *)`.
_STATIC: tuple[Entry, ...] = (

    Entry('roman', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|roman',
          summary='An integer in Roman numerals. 1 to 3999.',
          example='(* n|roman *)', expect='III'),
    Entry('nth', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|nth',
          summary='An English ordinal: `3rd`. Gets the teens right.',
          example='(* n|nth *)', expect='3rd'),
    Entry('upnth', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|upnth',
          summary='The same with the suffix superscripted, as maths.',
          example='(* n|upnth *)', expect='$3^{\\mathrm{rd}}$'),
    Entry('plural', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|plural(one, two, many)',
          summary='Pick a form by count, on the Slavic one/two-to-four/many split.',
          example="(* n|plural('úloha', 'úlohy', 'úloh') *)", expect='úlohy'),
    Entry('format_list', 'filter', env=STATIC, section='`.jtex` templates only',
          signature="|format_list(and_word='a', oxford_comma=False)",
          summary='Join a list with commas and a conjunction before the last item.',
          example='(* team|format_list *)', expect='Jana Nováková, Peter Novák a Eva Horváthová'),
    Entry('format_people', 'filter', env=STATIC, section='`.jtex` templates only',
          signature="|format_people(and_word='a')",
          summary='The same over `{name, gender}` entries, which is how `authors:` and '
                  '`evaluators:` are written. A nameless entry becomes a red error box rather '
                  'than a gap.',
          example='(* people|format_people *)', expect='Jana Nováková'),
    Entry('format_gender_suffix', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|format_gender_suffix',
          summary='The Slovak participle ending for one or more people -- `""`, `a`, `o`, `i`.',
          note="An undeclared gender gives `\\errorMessage{?}`, so a missing `gender:` key is "
               'visible on the page rather than silently masculine.',
          example='pripravil(* people|format_gender_suffix *)', expect='pripravila'),
    Entry('isotex', 'filter', env=STATIC, section='`.jtex` templates only',
          signature='|isotex',
          summary='A date as `YYYY--MM--DD`, the en dashes already escaped for TeX.',
          example='(* date|isotex *)', expect='2025--10--02'),

    Entry('plural', 'global', env=STATIC, section='`.jtex` templates only',
          signature='plural(how_many, one, two, many)',
          summary='The same as the filter, called rather than piped.',
          example="(* plural(n, 'úloha', 'úlohy', 'úloh') *)", expect='úlohy'),
    Entry('textbf', 'global', env=STATIC, section='`.jtex` templates only',
          signature='textbf(x)',
          summary=r'Wrap in `\textbf{}`.',
          example='(* textbf(n) *)', expect='\\textbf{3}'),
    Entry('path_exists', 'global', env=STATIC, section='`.jtex` templates only',
          signature='path_exists(path)',
          summary='`os.path.exists`, for a template that includes a figure only if it is there.'),
    Entry('file_size', 'global', env=STATIC, section='`.jtex` templates only',
          signature='file_size(path)',
          summary='`os.path.getsize`. Used to tell an empty generated file from a real one.'),
)


#: Jinja's own, listed because authors write them and a reference that goes blank on `|indent`
#: reads as broken. These three are the ones that appear in `source/`.
_BUILTINS: tuple[Entry, ...] = (

    Entry('indent', 'jinja-builtin', section="Jinja's own",
          signature='|indent(4)',
          summary='Indent every line but the first. **This is how an equation goes inside a list '
                  'item.**',
          note='`disp` and `align` close at column 0 whatever indent the tag sits at, so a bare '
               '`(§ eq.x|disp(\'.\') §)` inside a bullet puts its `$$ {#eq:…}` flush left and '
               'breaks out of the list. The defaults are exactly right: `first=False` because '
               "the tag's own indent already covers the opening `$$`, and `blank=False` so no "
               'trailing whitespace is invented. `include()` chains it the same way.',
          example="-   (§ eq.kin|disp('.')|indent(4) §)", expect='-   $$\n'
                                                          '        E_\\text{kin} = \\frac{1}{2} m v^2.\n'
                                                          '    $$ {#eq:demo:kin}'),
    Entry('format', 'jinja-builtin', section="Jinja's own",
          signature="|format(a, b)",
          summary="Python's `%` interpolation. Mostly seen building a path or an id.",
          example="(§ '%s-%02d'|format('fig', 7) §)", expect='fig-07'),
    Entry('float', 'jinja-builtin', section="Jinja's own",
          signature='|float',
          summary='Coerce to a float, with `0.0` on failure. Rarely needed -- `values:` already '
                  'parses numbers.',
          example='(§ "2.5"|float|f1 §)', expect='2.5'),
)


#: A problem's `meta.yaml`. The schema is `core/builder/renderer.py` merged with
#: `modules/naboj/builder/renderer.py`, and it is **closed at the top level** -- a key not listed
#: here fails validation with `Wrong key`.
#: The two names the context adds that are not written in a `meta.yaml` at all. Both are reached
#: by a dot, and neither is a quantity, which is why `highlight.js` must not read what follows the
#: dot as an attribute: `const.g` is a constant, not `g` of something.
_NAMESPACES: tuple[Entry, ...] = (

    Entry('const', 'namespace', section='Namespaces the context adds',
          signature='const.<name>',
          summary='The physical constants, from `core/data/constants.yaml`. Reached as '
                  '`(§ const.g §)`, and their symbols are already declared.',
          note='**A constant has two admissible values, and that is why an answer interval is a '
               'span:** the figure in `constants.yaml`, and the one the constants sheet prints -- '
               "that constant's `digits:` applied, which is what `.approx` returns. The "
               'competitor is holding the sheet, so both are legitimate arithmetic. A value there '
               'is **measured unless it says `exact: true`**, which is the opposite default to a '
               "`values:` entry, because a number a statement gives is exact and a measurement is "
               'not.',
          example='(§ const.g.eq §) and (§ const.g.approx.eq §)', expect='g \\approx \\qty{9.80665}{\\metre\\per\\second\\squared} and g \\approx \\qty{9.8}{\\metre\\per\\second\\squared}'),
    Entry('i18n', 'namespace', section='Namespaces the context adds',
          signature="i18n.<word>  ·  i18n.words['and']",
          summary='The recurring translated words, from `core/i18n/<lang>.yaml`. For a word '
                  'belonging to one problem, use `words:` in its meta instead.',
          note='`and` and `or` are Jinja keywords, so they are spelled `i18n.andw` and `i18n.orw`; '
               'everything else is spelled as written. `(§ i18n.words[\'and\'] §)` is the older '
               'form and still works. **There is no fallback to English and never was** -- a word '
               'a language has not got is boxed in red, reported at the end of the render, and the '
               'render then exits nonzero.'),
)


_META: tuple[Entry, ...] = (

    Entry('values', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='values: {name: {magnitude, unit, symbol, ...}}',
          summary='A quantity the **statement gives**. Spread into the top-level namespace, so '
                  '`values: {h: …}` is reached as `(§ h §)`.',
          note='A bare string, float or int is also accepted and passes through verbatim -- but '
               'the name then claims the text is a number the statement gives, which is what '
               '`blocks:` is for instead. `values:` names are checked against `RESERVED_NAMES` '
               '(`blocks`, `const`, `eq`, `i18n`, `words`).'),
    Entry('derived', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='derived: {name: "<jinja expression>"}',
          summary='A computed quantity. Each value is evaluated as a **Jinja expression**, in '
                  'document order, so a later entry sees the earlier ones.',
          note='An expression, not a template: anything with two statements in it fails as '
               '`TemplateSyntaxError: chunk after expression`. **An answer belongs here** -- a typed '
               'number in `answer.md` is the `answer-literal` finding, and the answer should be '
               '`result` printed as `(§ result §)`, so that changing an input changes the answer. '
               'This is also where `PQ`, `QL` and `.to()` are usually written.'),
    Entry('eq', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='eq: {name: "<latex>"}',
          summary='A block equation, hoisted out of the per-language files so there is one copy. '
                  'Reached as `(§ eq.name|disp(\'.\') §)`; **the key becomes the label**, '
                  '`{#eq:<pid>:<key>}`.',
          note='Hoisting removes the per-language latitude a translator has, deliberately: the '
               'physics is the same in every language and copies drift. An equation written out once '
               'per language has been known to lose a minus sign in one of them, so that one booklet '
               'told its readers the opposite of what the others did, and nothing reported it. A '
               'troll answer, an argument only prose carries, or a derivation that genuinely differs '
               'per language is worth leaving alone. Long entries wrap as a `|` block scalar -- '
               'write `|2` if the first row is indented deeper than the rest.'),
    Entry('words', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='words: {term: {lang: text}}',
          summary='A word that appears **inside maths** and has to change with the language. '
                  'Namespaced: `(§ words.air §)`.',
          note='The alternative is a copy of the equation per language, which is how the copies '
               'drift apart. A word belonging to one problem is the common case; a recurring one -- '
               '`and`, `or` -- belongs in `core/i18n/<lang>.yaml` instead. **There is no fallback**: '
               'a missing word is boxed in red, every miss is reported at the end of the render, and '
               'the render then exits nonzero.'),
    Entry('blocks', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='blocks: {name: |\\n  <text>}',
          summary='Text that comes back **verbatim**, namespaced as `(§ blocks.name §)`. The '
                  'one content key that does nothing to what it holds.',
          note='The case it exists for is a gnuplot preamble shared by several plots. **`|`, '
               'never `>`** -- a folded scalar collapses newlines into spaces and gnuplot wants '
               'one directive per line. Tags inside a block are expanded by the second pass, so a '
               'preamble can write `tcold = (§ tcold.mag §)` and stay in step.'),
    Entry('authors', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='authors: {idea: [...], problem: [...], solution: [...]}',
          summary='**Required.** Who did which of the three jobs. Each role is a list of names, '
                  'possibly empty.',
          note='Not read by the renderer; consumed by the audit and by the booklet credits. A '
               "**volume** meta carries an `authors:` too, and it is a different shape -- the "
               "booklet's four credit lists rather than one problem's three roles."),
    Entry('tags', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='tags: [mechanics, ...]',
          summary='**Required**, and validated against a fixed vocabulary. May be empty.'),
    Entry('audit', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature="audit: {ignore: ['answer-literal']}",
          summary='Opt a problem out of a named audit check, **with the reason written beside '
                  'it**.',
          note='Some answers are not the output of a calculation and no amount of `derived:` will '
               'make them one -- an answer that is 100 % whatever the inputs are, one that is zero '
               'by a symmetry, one that names which of several things is left over. Those cannot '
               'satisfy `answer-literal`. The reason written beside the ignore is the point of the '
               'key: an unexplained ignore is indistinguishable from a bug.'),
    Entry('similar', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='similar: [other-problem-id]',
          summary='**Read by nothing.** In the schema so that a meta carrying it still validates.'),
    Entry('difficulty', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='difficulty: 3',
          summary='**Read by nothing**, like `similar`.'),
    Entry('physics', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='physics: 3',
          summary='**Read by nothing**, like `similar`.'),
    Entry('math', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='math: 3',
          summary='**Read by nothing**, like `similar`.'),
    Entry('id', 'meta-key', env=META, section='`meta.yaml`: a problem',
          signature='id',
          summary='**Not written by an author** in a problem meta -- injected from the directory '
                  'name, and used to build each equation label.',
          note='A **venue** meta does write one, and a competition meta writes its own; the '
               'volume and language levels have theirs injected like a problem.'),

    Entry('magnitude', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='magnitude: 9.81',
          summary='**Required.** The number.',
          note='**Scientific notation must be written `1.0e+15`.** YAML 1.1 wants both a decimal '
               'point *and* a sign before it reads an exponent as a number, so `1e15`, `1e+15` and '
               '`1.0e15` all parse as bare **strings**. The schema rejects a string here for exactly '
               'that reason and names the key; before it did, the first sign of trouble was a '
               '`derived:` expression reporting `unsupported operand type(s) for /`, a long way from '
               'the cause.'),
    Entry('unit', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature=r'unit: \metre\per\second',
          summary='The unit. Defaults to dimensionless.',
          note='**Spell it the way pint spells it**, because `values:` and `derived:` render '
               'through pint and anything else blocks a hoist: `\\kilo\\gram` not `\\kilogram`, '
               '`\\metre\\cubed` not `\\cubic\\metre`, `\\metre` not `\\meter`. All three pairs '
               'are identical on the page, so this is a source convention -- but a solution '
               'writing the unit the other way cannot be pointed at the value holding the same '
               'number, because the rendered output moves.'),
    Entry('symbol', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature=r'symbol: \rho',
          summary='The LaTeX symbol this quantity is named by. **Defaults to the entry\'s own '
                  'name**, which is usually not what you want.',
          note='Declaring it here is what lets the source write `$(§ rho.eq §)$` as one tag '
                  'instead of `$\\rho = (§ rho §)$`.'),
    Entry('digits', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='digits: 3',
          summary='How many figures to **print**. Presentation only -- independent of `exact`, '
                  'and it does not propagate through arithmetic.'),
    Entry('exact', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='exact: false',
          summary='Whether the value is the true one. **Defaults to `true`** here, because a '
                  'number a statement gives is exact.',
          note="The opposite default to `constants.yaml`, where a value is measured unless it "
               'says otherwise. Set it false for a given that is itself an approximation.'),
    Entry('si_extra', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='si_extra: {per-mode: symbol}',
          summary='siunitx options passed through to the `\\qty[...]` call.'),
    Entry('force_f', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='force_f: true',
          summary='Never write this value as a power of ten: print it fixed, to its own length. '
                  'An explicit precision such as `|f2` still wins -- this replaces the notation, '
                  'not the number of figures.'),
    Entry('aliases', 'values-key', env=META, section='`meta.yaml`: a `values:` entry',
          signature='aliases: [...]',
          summary='Alternative names, for a constants file. Accepted on a problem `values:` entry, '
                  'where nothing reads it.'),
)


#: The other four levels of `meta.yaml`. A problem's is the one anybody edits often, but the
#: hierarchy has a meta at every level and each has its own closed schema, so a key that is legal
#: in one is a validation error in the next.
_HIERARCHY: tuple[Entry, ...] = (

    Entry('problems', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='problems: [first-problem, second-problem, ...]',
          summary='The volume\'s running order, and the **only** thing that puts a problem in a '
                  'booklet.',
          note='This list *is* the running order and is what `ContextVolume` iterates. A problem '
               'missing from it is never built; one listed without a directory gets '
               "`\\protectedInput`'s red `Missing file` box, which is the intended behaviour -- a "
               'hole in a booklet should be loud. The audit checks both directions, as '
               '`unit-unlisted` and `listed-missing`.'),
    Entry('date', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='date: 2025-11-14', summary='The day the competition is held.'),
    Entry('start', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='start: 10:00',
          summary='When it starts. A **venue** meta may override it with its own.'),
    Entry('workshop', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='workshop: ...', summary='The accompanying workshop, for the booklet.'),
    Entry('table', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='table: ...', summary='The answer table printed at the back of the booklet.'),
    Entry('constants', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='constants: [g, c, ...]',
          summary='Which constants the sheet prints -- and therefore, through each one\'s '
                  '`digits:`, what `.approx` is allowed to be.'),
    Entry('venues', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='venues: {...}',
          summary='Venues written inline rather than as their own directories.'),
    Entry('orgs', 'meta-key', env=META, section='`meta.yaml`: a volume',
          signature='orgs: [...]',
          summary='Organisers, on a volume or on a venue. The documented legacy escape hatch.'),

    Entry('booklet', 'meta-key', env=META, section='`meta.yaml`: a language',
          signature='booklet: ...',
          summary="The booklet's own per-language settings, in "
                  '`<volume>/languages/<lang>/meta.yaml`.'),
    Entry('translators', 'meta-key', env=META, section='`meta.yaml`: a language',
          signature='translators: [...]', summary='Who translated this language, for the credits.'),

    Entry('name', 'meta-key', env=META, section='`meta.yaml`: a venue',
          signature='name: Bratislava', summary='The venue, as the booklet prints it.'),
    Entry('code', 'meta-key', env=META, section='`meta.yaml`: a venue',
          signature='code: BA', summary='The short code that goes into a team number.'),
    Entry('language', 'meta-key', env=META, section='`meta.yaml`: a venue',
          signature='language: sk', summary='Which language booklet this venue is sent.'),
    Entry('evaluators', 'meta-key', env=META, section='`meta.yaml`: a venue',
          signature='evaluators: [...]', summary='Who marks there.'),

    Entry('hacks', 'meta-key', env=META, section='`meta.yaml`: the competition',
          signature='hacks: ...',
          summary='Per-competition overrides, in `source/naboj/<competition>/meta.yaml`.'),
    Entry('tearoff', 'meta-key', env=META, section='`meta.yaml`: the competition',
          signature='tearoff: ...', summary='The tear-off answer slip.'),
    Entry('url', 'meta-key', env=META, section='`meta.yaml`: the competition',
          signature='url: https://...', summary="The competition's own address."),
    Entry('organisation', 'meta-key', env=META, section='`meta.yaml`: the competition',
          signature='organisation: ...', summary='Who runs it.'),
)


#: Everything, in the order the document prints it.
REFERENCE: tuple[Entry, ...] = (_FILTERS + _GLOBALS + _ATTRIBUTES + _STATIC + _BUILTINS
                                + _NAMESPACES + _META + _HIERARCHY)


# --------------------------------------------------------------------------- lookup

def index() -> dict[tuple[str, str], Entry]:
    """
    Every name an author may write, keyed by `(kind, name)`.

    Keyed by the pair and not by the name alone because several names mean different things in
    different places and the right answer depends on where the cursor is: `unit` is a filter, an
    attribute **and** a `values:` key; `mag` and `eq` are each two of those; `plural` is both a
    filter and a global in a `.jtex`. The editor knows which it found -- that is what `data-ref`
    carries -- so it asks for the pair.
    """
    built = {}
    for entry in REFERENCE:
        for name in entry.names:
            built[(entry.kind, name)] = entry
    return built


def lookup(name: str, *, kind: str | None = None, env: str | None = None) -> Entry | None:
    """One entry, or `None`. With no `kind`, the first that matches in document order."""
    for entry in REFERENCE:
        if name not in entry.names:
            continue
        if kind is not None and entry.kind != kind:
            continue
        if env is not None and entry.env != env:
            continue
        return entry
    return None


def as_json() -> dict:
    """
    The whole table in the shape `/api/reference` serves and the editor's hover reads.

    Keyed `"<kind>:<name>"`, which is exactly what `highlight.js` puts in `data-ref`, so the
    front end does one dictionary lookup and no parsing.
    """
    payload = {}
    for entry in REFERENCE:
        # A Jinja builtin is *written* with a pipe, so `highlight.js` cannot tell it from one of
        # ours and asks for `filter:indent`. Answering under both keys is the whole reason the
        # builtins are in the table: a hover that goes blank on `|indent` -- which 16 sources
        # write, and which is how an equation goes inside a list item -- reads as broken.
        keys = ('filter', entry.kind) if entry.kind == 'jinja-builtin' else (entry.kind,)
        for name in entry.names:
            for key in keys:
                payload[f'{key}:{name}'] = {
                    'name': name,
                    'kind': entry.kind,
                    'env': entry.env,
                    'display': entry.display,
                    'signature': entry.signature,
                    'summary': entry.summary,
                    'note': entry.note,
                    'example': entry.example,
                    'expect': entry.expect,
                    # A precision variant is documented by its root; say which root it came from.
                    'root': entry.name,
                }
    return {'entries': payload, 'sections': list(dict.fromkeys(e.section for e in REFERENCE))}


# ------------------------------------------------------------------------- document

#: What the head of the document says before the table starts. Kept here rather than in a
#: template so that the generator is one file and `--check` has one thing to compare.
PREAMBLE = """\
# The Jinja vocabulary

Every filter, global, attribute and `meta.yaml` key an author may write, with an example of each.

**This file is generated.** It is written by `python -m core.builder.reference`, from the table in
`core/builder/reference.py`, and `core/tests/test_reference.py` asserts three things about it: that
the table's names are exactly the names the renderers register, in both directions; that every
example below renders to the output printed beneath it; and that this file matches what the
generator produces. So editing it by hand will be undone, and a filter added without an entry
fails the suite.

Two environments, and they are **disjoint**:

| you are editing | environment | a variable is written | and it has |
|---|---|---|---|
| `.md`, and `.svg` / `.tikz` / `.gp` | `MarkdownJinjaRenderer` | `(§ x §)` | {markdown_filters} filters, {markdown_globals} globals |
| `.jtex` | `StaticRenderer` | `(* x *)` | {static_filters} filters, {static_globals} globals |

`|disp` works only in the first and `|upnth` only in the second. Neither renderer sees the
other's table, so the mistake is found by a failed build.

A filter family written `|f0 … |f9` is one function with a precision baked in: `|f2` is `|f` to
two places, and a bare `|f` prints whatever the value has. All {generated} of those are
generated, so they behave identically and are documented once, under the root.

## The examples

Every example below is rendered in this context, which is what `example_context()` builds:

{context}

"""


def _context_table() -> str:
    """The example context, printed once so an example reads without hunting for what `v` is."""
    rows = [
        ('`v`', r'`\qty{3}{\metre\per\second}`', 'a given, so **exact**'),
        ('`m`', r'`\qty{1.5}{\kilo\gram}`', 'a given'),
        ('`d`', r'`\qty{5}{\kilo\metre}`', 'a given'),
        ('`rho`', r'`\qty{1000}{\kilo\gram\per\metre\cubed}`', r'symbol `\rho`'),
        ('`E`', r'`\qty{1.602176634e-19}{\joule}`', 'small enough to need an exponent'),
        ('`frac`', '`1.00356e-4`', "dimensionless, and the case `|e` exists for"),
        ('`alpha`', r'`\qty{44.15}{\degree}`', 'an angle'),
        ('`c_s`', r'`\qty{343}{\metre\per\second}`',
         'a **measured** constant, `digits: 3` -- so `.eq` writes `\\approx`'),
        ('`result`, `result_approx`', '`64.5663 d`, `64.5665 d`',
         'the pair an answer interval spans'),
        ('`sides`', '`QL(1 m, 2 m, 3 m)`', 'a list'),
        ('`box`', '`QP(3 cm, 4 cm, 5 cm)`', 'a product'),
        ('`eq.kin`', r'`E_\text{kin} = \frac{1}{2} m v^2`', 'a `MathObject`'),
        ('`eq.chain`', '`a &= b \\\\ &= c`', 'a chain, for `|align`'),
        ('`eq.sys`', '`x &+& y &=& 1 \\\\ x &-& y &=& 0`', 'a system, for `|arr`'),
        ('`const.g`', r'`\qty{9.80665}{\metre\per\second\squared}`',
         'measured, `digits: 2` -- so `.approx` is `9.8`'),
        ('`words.air`', '`vzduch`', 'a `words:` entry'),
        ('`n`, `team`, `people`, `date`', '`3`, three names, one author, 2025-10-02',
         'for the `.jtex` examples'),
    ]
    # A pipe inside a cell ends the cell, so `|align` has to be escaped to survive the table.
    def cell(text):
        return text.replace('|', r'\|')

    out = ['| name | value | |', '|---|---|---|']
    out += [f'| {cell(name)} | {cell(value)} | {cell(why)} |' for name, value, why in rows]
    return '\n'.join(out)


def _wrap(text: str) -> str:
    """
    Prose wrapped at the width the rest of the repository is written to.

    Worth doing although the file is generated: it is read in a terminal and in a diff, and a
    400-character paragraph is unreadable in both. Regeneration rewrites the file whole, so the
    churn a rewrap would cause in a hand-maintained file does not arise here.
    """
    import textwrap
    return '\n'.join(textwrap.wrap(text, width=100, break_long_words=False,
                                   break_on_hyphens=False))


def _block(text: str) -> str:
    """An indented code block, so an example containing a fence cannot break out of one."""
    return '\n'.join(f'    {line}' if line else '' for line in text.split('\n'))


def render_markdown() -> str:
    """The whole document, deterministically."""
    import jinja2

    from core.builder.jinja import MarkdownJinjaRenderer, StaticRenderer

    base = jinja2.Environment()
    markdown, static = MarkdownJinjaRenderer(), StaticRenderer('.')
    counts = {
        'markdown_filters': len([k for k in markdown.env.filters
                                 if k not in base.filters or k == 'e']),
        'markdown_globals': len([k for k in markdown.env.globals if k not in base.globals]),
        'static_filters': len([k for k in static.env.filters if k not in base.filters]),
        'static_globals': len([k for k in static.env.globals if k not in base.globals]),
        'generated': sum(len(PRECISIONS) * len((e.name, *e.aliases))
                         for e in REFERENCE if e.precisions),
    }

    out = [PREAMBLE.format(context=_context_table(), **counts)]
    section = None
    for entry in REFERENCE:
        if entry.section != section:
            section = entry.section
            out.append(f'## {section}\n')

        heading = f'`{entry.display}`'
        if entry.precisions:
            heading += f' · `{entry.display}0` … `{entry.display}9`'
        out.append(f'### {heading}\n')
        # The signature earns a line only when it says more than the heading already does --
        # which it does for everything that takes an argument, and for nothing that does not.
        if entry.signature and entry.signature != entry.display:
            out.append(f'`{entry.signature}`\n')
        out.append(_wrap(entry.summary) + '\n')
        if entry.note:
            out.append(_wrap(entry.note) + '\n')
        if entry.example:
            out.append(_block(entry.example))
            out.append('\nproduces\n')
            out.append(_block(entry.expect))
            out.append('')

    return '\n'.join(out).rstrip('\n') + '\n'


# ------------------------------------------------------------------------------ CLI

def main():
    """
    `python -m core.builder.reference` -- write `docs/filters.md`; `--check` compares instead.

    The same shape as `core/audit/macros.py`: run it to refresh, run it with `--check` in CI.
    """
    import argparse

    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument('--check', action='store_true',
                        help='compare against the file on disk; exit 1 if it is stale')
    args = parser.parse_args()

    generated = render_markdown()
    if not args.check:
        DOCUMENT.parent.mkdir(parents=True, exist_ok=True)
        DOCUMENT.write_text(generated)
        print(f'{DOCUMENT}: {len(REFERENCE)} entries, '
              f'{len({n for e in REFERENCE for n in e.names})} names')
        raise SystemExit(0)

    if not DOCUMENT.is_file():
        print(f'{DOCUMENT} has never been generated')
        raise SystemExit(1)
    current = DOCUMENT.read_text()
    if current == generated:
        print(f'{DOCUMENT} is up to date')
        raise SystemExit(0)

    diff = difflib.unified_diff(current.splitlines(), generated.splitlines(),
                                fromfile=f'{DOCUMENT} (on disk)', tofile='(generated)', lineterm='')
    print(f'{DOCUMENT} is stale; run `python -m core.builder.reference`')
    for line in diff:
        print(line, file=sys.stderr)
    raise SystemExit(1)


if __name__ == '__main__':
    main()
