name: Makefile CI

on:
  workflow_run:
    workflows: ["Install DeGeŠ"]
    branches: [testing]
    types: 
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Clone testing repository"
      uses: actions/checkout@master
      with:
        repository: TrojstenSK/dgs-seminar-testing
        path: source/seminar/testing
    - name: "Build testing 01/1/1"
      run: |
        make output/seminar/testing/01/1/1
    
